[package]
name = "ping-pong-boxes"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
strip = true
lto = "fat"

[dependencies]
rand = "0.8.5"
slint = "1.9.2"

[build-dependencies]
slint-build = "1.9.2"
