export struct Vec2 {
    vx:length,
    vy:length,
}

export struct Data { 
    speed: Vec2,
    x: length,
    y: length,
    color: color,
}

export component App inherits Window {
    preferred-width: 500px;
    preferred-height: 500px;
    background: #202424;
    callback update();
    property <duration> elapsed: 1s / 60;
    in-out property <[Data]> boxs;
    in-out property <length> side_len;
    in-out property <length> win_width <=> self.width;
    in-out property <length> win_height <=> self.height;
    for abox in boxs: Rectangle {
        width: side_len;
        height: side_len;
        background: abox.color;
        x: abox.x;
        y: abox.y;
        animate x, y {
            duration: elapsed;
            easing: ease;
        }
    }
    Timer {
        interval: elapsed;
        triggered => {
            update();
        }
    }
}
